coverage:
  status:
    project:
      default:
        target: 100%
        threshold: 0%
    patch:
      default:
        target: 100%
        threshold: 0%

ignore:
  - "src/components"
  - "src/i18n"
  - "src/store"
  - "environment.js"
